services:
  workspace:
    container_name: docker_test_devcontainer
    image: mcr.microsoft.com/devcontainers/base:bullseye
    command: sleep infinity

    ports:
      - "5173:5173" # 프론트엔드 (Vite 개발 서버)

    volumes:
      - ..:${containerWorkspaceFolder}:cached

    environment:
      - TZ=Asia/Seoul
